import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const Custom404: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col align-middle min-h-screen bg-gray-900 font-Poppins text-gray-400">
        <Navbar />
        <div className="flex flex-col item-center justify-center flex-1 p-10 lg:px-20">
          <h1 className="text-5xl md:text-6xl font-bold text-teal-600">404 Error</h1>
          <h3 className="text-xl">Praying that you find what you're looking for! 🙏</h3>
        </div>
        <Footer />
      </main>
    </>
  );
};

export default Custom404;