import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Navbar from "../components/Navbar";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.prayerBoard.hello.useQuery({ name: "Ben" })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-lightCyan font-Poppins">
        <Navbar />
        
      </main>
    </>
  );
};

export default Home;
