import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import Navbar from "../components/Navbar";
import PrayingPerson from "../components/PrayingPerson";
import AllStats from "../components/AllStats";
import Footer from "../components/Footer";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col align-middle min-h-screen bg-gray-900 font-Poppins text-gray-400">
        <Navbar />
        <div className="flex flex-1 items-center p-10 lg:px-20 justify-around flex-col-reverse lg:flex-row">
          <div>
            <PrayingPerson />
          </div>
          <div className="flex flex-col justify-center gap-7 lg:max-w-xxl text-right pb-12">
            <h1 className="text-5xl md:text-7xl font-bold text-gray-300">Everyone needs <span className="text-cyan-700">prayer</span></h1>
            <p className="text-xl md:text-2xl">Create a community of prayer.<br/>Create a <span className="font-bold">PrayerBoard</span>.</p>
            <div className="flex justify-end gap-7 font-medium text-lg flex-col sm:flex-row">
              <Link className="rounded-full hover:bg-teal-700 bg-teal-800 text-cyan-50 p-1.5 px-5 text-center transition-colors" href="/dashboard">Visit Board</Link>
              <Link className="rounded-full hover:bg-cyan-700 bg-cyan-800 text-cyan-50 p-1.5 px-5 text-center transition-colors" href="/create">Create Board</Link>
            </div>
            <AllStats />
          </div>
          
        </div>
        <Footer />
      </main>
    </>
  );
};

export default Home;
